<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>ISpy.Media</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="9.0.1.1" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ISpy.Core/ISpy.Core.csproj" />
  </ItemGroup>
</Project>
